CREATE DATABASE exercicio
  WITH OWNER = postgres
       ENCODING = 'UTF8'
       TABLESPACE = pg_default
       LC_COLLATE = 'en_US.utf8'
       LC_CTYPE = 'en_US.utf8'
       CONNECTION LIMIT = -1;

\c exercicio


CREATE TABLE public.funcionario
(
  id integer NOT NULL,
  nome character(30),
  vl_salario_bruto numeric(8,2),
    CONSTRAINT funcionario_pkey PRIMARY KEY (id)
);

CREATE TABLE public.desconto
(
  id integer NOT NULL,
  id_funcionario integer,
  vl_desconto numeric(5,2),
    CONSTRAINT desconto_pkey PRIMARY KEY (id)
);


INSERT INTO FUNCIONARIO (ID, NOME, VL_SALARIO_BRUTO) VALUES (1, 'JOAO I', 1000.00);
INSERT INTO FUNCIONARIO (ID, NOME, VL_SALARIO_BRUTO) VALUES (2, 'JOAO II', 1200.00);
INSERT INTO FUNCIONARIO (ID, NOME, VL_SALARIO_BRUTO) VALUES (3, 'JOAO III', 1500.00);
INSERT INTO FUNCIONARIO (ID, NOME, VL_SALARIO_BRUTO) VALUES (4, 'MARIA I', 1200.00);
INSERT INTO FUNCIONARIO (ID, NOME, VL_SALARIO_BRUTO) VALUES (5, 'MARIA II', 1700.00);
INSERT INTO FUNCIONARIO (ID, NOME, VL_SALARIO_BRUTO) VALUES (6, 'MARIA III', 1100.00);

INSERT INTO DESCONTO (ID, ID_FUNCIONARIO, VL_DESCONTO) VALUES (1, 1, 10.00);
INSERT INTO DESCONTO (ID, ID_FUNCIONARIO, VL_DESCONTO) VALUES (2, 2, 20.00);
INSERT INTO DESCONTO (ID, ID_FUNCIONARIO, VL_DESCONTO) VALUES (3, 3, 40.00);
INSERT INTO DESCONTO (ID, ID_FUNCIONARIO, VL_DESCONTO) VALUES (4, 4, 25.00);
INSERT INTO DESCONTO (ID, ID_FUNCIONARIO, VL_DESCONTO) VALUES (5, 5, 30.00);
INSERT INTO DESCONTO (ID, ID_FUNCIONARIO, VL_DESCONTO) VALUES (6, 6, 10.00);